Madonahs/Developers-Portfolio

app/build.gradle

Add libraries that may helps us to select view from layout easier and more elegant with Butter Knife
http://jakewharton.github.io/butterknife/
And Dagger for dependency injection
https://google.github.io/dagger/android.html

Add Libraries

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ProfileActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/intro/OnBoardingActivity.java
app/src/main/res/layout/activity_profile.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/strings.xml

Add the intro activity and profile activity. Including some new libraries like butterknife and dagger

Login register activities

---

.idea/misc.xml
app/build.gradle
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/LoginFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/RegisterFragment.java
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_login.xml
app/src/main/res/layout/fragment_register.xml
gradle.properties

Added data binding support to avoid the expensive id look up using findViewBy

added data binding support

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/RegisterFragment.java
app/src/main/res/layout/activity_profile.xml

* Resolved conflict with Emmanuels commit
* [ Data binding doc](https://developer.android.com/topic/libraries/data-binding/index.html)

Resolved conflict

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ProfileActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/interfaces/OnFragmentInteractionListener.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/FeedsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/InterestFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProjectsFragment.java
app/src/main/res/layout/activity_main.xml

Refactor OnFragmentInteractionListener

Refactor OnFragmentInteractionListener

---

.idea/misc.xml
.idea/modules.xml
CONTRIBUTING.md
README.md
app/build.gradle
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/User.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/res/drawable/button_transparent_no_stroke.xml
app/src/main/res/drawable/button_transparent_normal_no_stroke.xml
app/src/main/res/drawable/ic_offline.xml
app/src/main/res/drawable/ic_online.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

* delete branch CleverChuk-profileActivity
* rename branch profileActivity to profile-fragment

master clean and up to date

---

LICENSE.txt
README.md
app/src/main/AndroidManifest.xml
app/src/main/res/values/styles.xml

Getting the latest changes from master to google-login

Getting the latest changes from Master

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/login/AppLoginManager.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/LoginFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/RegisterFragment.java

Change package name, fix bug when text input are empty

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/login/LoginStatusManager.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/res/values/strings.xml

After using logging we have to store if user is logged or not, now it applied only for firebase connection, it will be used for other logging type after refactoring and adding logout.

Add store login status

---

.idea/misc.xml
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ProfileActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/dialogs/ProfileFragmentDialog.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/res/layout/activity_profile.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/values/styles.xml

Profile fragment

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/login/AppLoginManager.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java

Just add method that will be called to reset password for firebase.

Add reset password

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/dialogs/ProfileFragmentDialog.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/User.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/Constant.java
app/src/main/res/layout/fragment_profile.xml

Remove Crappy Codes

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/InterestActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/dialogs/ProfileFragmentDialog.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/User.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/FeedsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/InterestFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProjectsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/RegisterFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/Constant.java
app/src/main/res/layout/fragment_profile.xml

Profile activity

---

.gitignore
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/interfaces/Callback.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/FirebaseObject.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/Paths.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/User.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/FirebaseAction.java

This is a working test only, need to properly create or update user based on logical flow of application. For now, it creates a user after profile fragment is submitted - this isn't the correct action however should help anyone who wants to perform CRUD operations on firebase.

Firebase helper

---

app/build.gradle
app/dependencies.gradle

Gradle refinements

---

.idea/modules.xml
README.md
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/actvities/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/login/LoginStatusManager.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/LoginActivity.java

Log out issue #112 (Messed it up in the commit :laughing: )
This commit resolves the log out issues.

Issue #122

---

app/src/main/res/layout-sw600dp/addcomment.xml
app/src/main/res/layout-sw600dp/comment.xml
app/src/main/res/layout-sw600dp/interest_list_row.xml
app/src/main/res/layout-sw600dp/message_row.xml

Screen Compatibility 

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/activities/LoginActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/activities/MainActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/activities/PostActivity.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/adapter/FeedsAdapter.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/FeedsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/HelpFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ImageDialog.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/InterestFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/LoginFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/PostFeedFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProfileFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ProjectsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/RegisterFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/ViewPagerManagement.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/intro/OnBoardingActivity.java
app/src/main/res/layout-land/activity_login.xml
app/src/main/res/layout-sw600dp/activity_login.xml
app/src/main/res/layout/activity_login.xml
app/src/main/res/layout/fragment_feeds.xml
app/src/main/res/layout/fragment_help.xml
app/src/main/res/layout/fragment_interest.xml
app/src/main/res/layout/fragment_projects.xml
app/src/main/res/layout/portfolio_list_row.xml
app/src/main/res/values/strings.xml

Reverts Madonahs/Devsfolio#142

Revert "Moved fragment folder"

---

app/build.gradle

code inspection

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/adapter/FeedsAdapter.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/adapter/PortfolioAdapter.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/models/Post.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/FeedsFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/HelpFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/ui/fragment/PostFeedFragment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/BitmapHandler.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/Comment.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/GeoAddressUtil.java
app/src/main/java/com/madonasyombua/growwithgoogleteamproject/util/UserComment.java

Final touches

---

app/src/main/java/com/madonasyombua/growwithgoogleteamproject/login/AppLoginManager.java
app/src/main/res/values-an-rES/strings.xml
app/src/main/res/values-de-rDE/strings.xml
app/src/main/res/values-en-rGB/strings.xml
app/src/main/res/values-fi-rFI/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-zh-rCN/strings.xml
build.gradle

Check for duplicates
